"""Compatibility import bundle for scheduler.py.

Generated by splitting scheduler_compat_imports.py into domain-oriented import surfaces.
"""

from __future__ import annotations

from scheduler_task.ids import (
    allocate_task_id as _allocate_task_id,
    allocate_task_ids as _allocate_task_ids,
    format_task_id as _format_task_id,
    task_id_number as _task_id_number,
)
from scheduler_state.archive import (
    archive_terminal_tasks as _archive_terminal_tasks_impl,
    compact_age_days_from_args as _compact_age_days_from_args_impl,
    find_task_record as _find_task_record_impl,
    load_archive_tasks as _load_archive_tasks_impl,
    terminal_archive_stats as _terminal_archive_stats_impl,
)
from scheduler_result.batch_completion import (
    detect_batch_completions as _detect_batch_completions_impl,
    signature_batch_key as _signature_batch_key_impl,
)
from scheduler_commands.cli import (
    SchedulerCliDeps as _SchedulerCliDeps,
    run_scheduler_cli as _run_scheduler_cli,
)
from scheduler_commands.wiring import (
    build_adopt_command_deps as _build_adopt_command_deps,
    build_bulk_submit_deps as _build_bulk_submit_deps,
    build_edit_command_deps as _build_edit_command_deps,
    build_history_command_deps as _build_history_command_deps,
    build_scheduler_cli_deps as _build_scheduler_cli_deps,
    build_status_command_deps as _build_status_command_deps,
    build_submit_command_deps as _build_submit_command_deps,
    build_submit_cpu_batch_command_deps as _build_submit_cpu_batch_command_deps,
    build_submit_jsonl_command_deps as _build_submit_jsonl_command_deps,
    build_submit_preflight_deps as _build_submit_preflight_deps,
    build_submit_task_deps as _build_submit_task_deps,
    build_task_control_deps as _build_task_control_deps,
    build_why_command_deps as _build_why_command_deps,
)
from scheduler_diagnostics.wiring import (
    build_claim_manager_deps as _build_claim_manager_deps,
    build_crash_requeue_deps as _build_crash_requeue_deps,
    build_doctor_deps as _build_doctor_deps,
    build_profile_local_deps as _build_profile_local_deps,
    build_queued_artifact_reconcile_deps as _build_queued_artifact_reconcile_deps,
    build_resource_forensics_deps as _build_resource_forensics_deps,
    build_resource_history_deps as _build_resource_history_deps,
    build_result_artifact_deps as _build_result_artifact_deps,
    build_runtime_history_lookup_deps as _build_runtime_history_lookup_deps,
    build_runtime_history_record_deps as _build_runtime_history_record_deps,
    build_terminal_diagnosis_deps as _build_terminal_diagnosis_deps,
)
from scheduler_runtime.wiring import (
    build_adopt_probe_deps as _build_adopt_probe_deps,
    build_claim_tending_deps as _build_claim_tending_deps,
    build_docker_wrap_deps as _build_docker_wrap_deps,
    build_env_smoke_deps as _build_env_smoke_deps,
    build_eviction_deps as _build_eviction_deps,
    build_external_reconcile_deps as _build_external_reconcile_deps,
    build_launch_commit_deps as _build_launch_commit_deps,
    build_launch_cwd_staging_deps as _build_launch_cwd_staging_deps,
    build_launch_recovery_deps as _build_launch_recovery_deps,
    build_launch_staging_plan_deps as _build_launch_staging_plan_deps,
    build_local_orphan_recovery_deps as _build_local_orphan_recovery_deps,
    build_migration_policy_deps as _build_migration_policy_deps,
    build_migration_staging_deps as _build_migration_staging_deps,
    build_node_resource_gate_deps as _build_node_resource_gate_deps,
    build_notify_deps as _build_notify_deps,
    build_placement_runtime as _build_placement_runtime,
    build_post_dispatch_threshold_deps as _build_post_dispatch_threshold_deps,
    build_preemption_deps as _build_preemption_deps,
    build_resource_accounting_deps as _build_resource_accounting_deps,
    build_result_sync_executor_deps as _build_result_sync_executor_deps,
    build_resume_ckpt_staging_deps as _build_resume_ckpt_staging_deps,
    build_resume_fit_deps as _build_resume_fit_deps,
    build_resume_scan_deps as _build_resume_scan_deps,
    build_terminal_finalize_deps as _build_terminal_finalize_deps,
    build_wait_for_deps as _build_wait_for_deps,
)
from scheduler_display import (
    format_mem_gb as _format_mem_gb_impl,
    format_node_ram_summary as _format_node_ram_summary_impl,
    format_task_location as _format_task_location_impl,
    format_task_ram_usage as _format_task_ram_usage_impl,
    format_task_vram_usage as _format_task_vram_usage_impl,
)
from scheduler_state.compaction import (
    compact_resource_task_summary as _compact_resource_task_summary,
    compact_state_for_persistence as _compact_state_for_persistence,
)
from scheduler_state.runtime import (
    SchedulerLockTimeout,
    build_state_runtime_exports as _build_state_runtime_exports,
)

__all__ = [
    name
    for name in globals()
    if name != "__all__" and not (name.startswith("__") and name.endswith("__"))
]
