"""Compatibility import bundle for scheduler.py.

Generated by splitting scheduler_compat_imports.py into domain-oriented import surfaces.
"""

from __future__ import annotations

from scheduler_failure.analysis import (
    CompletedLogCrashScanDeps as _CompletedLogCrashScanDeps,
    FailureClassificationDeps as _FailureClassificationDeps,
    LogTailDeps as _LogTailDeps,
    classify_failure as _classify_failure_impl,
    fetch_log_tail as _fetch_log_tail_impl,
    scan_completed_log_for_crash as _scan_completed_log_for_crash_impl,
)
from scheduler_diagnostics.heal_escalation import (
    EscalationDeps as _EscalationDeps,
    HealSessionDeps as _HealSessionDeps,
    fire_heal_session as _fire_heal_session_impl,
    latest_escalations as _latest_escalations_impl,
    recover_resolved_staging_failures as _recover_resolved_staging_failures_impl,
    resolve_staged_cwd_escalations as _resolve_staged_cwd_escalations_impl,
    write_escalation as _write_escalation_impl,
)
from scheduler_adopt.probe import (
    AdoptProbeDeps as _AdoptProbeDeps,
    collect_external_task_probe_data as _collect_external_task_probe_data_impl,
    descendants_of as _descendants_of_impl,
    infer_adopt_cwd_from_cmdline as _infer_adopt_cwd_from_cmdline_impl,
    node_auto_adopt_owners as _node_auto_adopt_owners_impl,
    node_auto_adopt_roots as _node_auto_adopt_roots_impl,
    node_cpu_processes as _node_cpu_processes_impl,
    node_expected_process_owner as _node_expected_process_owner_impl,
    node_ppid_map as _node_ppid_map_impl,
    node_processes as _node_processes_impl,
    path_under_roots as _path_under_roots_impl,
    refresh_adopted_resources as _refresh_adopted_resources_impl,
)
from scheduler_eta.refresh import (
    EtaRefreshDeps as _EtaRefreshDeps,
    refresh_eta_from_logs as _refresh_eta_from_logs_impl,
)
from scheduler_eta.background import (
    EtaBackgroundRefreshDeps as _EtaBackgroundRefreshDeps,
    refresh_eta_snapshot as _refresh_eta_snapshot_impl,
    start_eta_periodic_refresh as _start_eta_periodic_refresh_impl,
    start_eta_refresh_background as _start_eta_refresh_background_impl,
    stop_eta_periodic_refresh as _stop_eta_periodic_refresh_impl,
)
from scheduler_eta.tail_snapshot import (
    EtaTailOutputDeps as _EtaTailOutputDeps,
    EtaTailSnapshotDeps as _EtaTailSnapshotDeps,
    eta_tail_outputs_by_node as _eta_tail_outputs_by_node_impl,
    eta_tail_snapshot_outside_lock as _eta_tail_snapshot_outside_lock_impl,
)
from scheduler_running.snapshots import (
    BatchCheckRunningDeps as _BatchCheckRunningDeps,
    RunningProbeSnapshotDeps as _RunningProbeSnapshotDeps,
    UpdateRunningTasksDeps as _UpdateRunningTasksDeps,
    batch_check_running as _batch_check_running_impl,
    effective_elapsed_s as _effective_elapsed_s_impl,
    running_probe_snapshot_outside_lock as _running_probe_snapshot_outside_lock_impl,
    update_running_tasks as _update_running_tasks_impl,
)
from scheduler_failure.terminal_snapshot import (
    TerminalDiagnosticsSnapshotDeps as _TerminalDiagnosticsSnapshotDeps,
    terminal_diagnostic_fingerprint as _terminal_diagnostic_fingerprint_impl,
    terminal_diagnostic_matches as _terminal_diagnostic_matches_impl,
    terminal_diagnostics_snapshot_outside_lock as _terminal_diagnostics_snapshot_outside_lock_impl,
)
from scheduler_probe.running_wiring import (
    build_batch_check_running_deps as _build_batch_check_running_deps,
    build_claim_probe_fold_deps as _build_claim_probe_fold_deps,
    build_eta_refresh_deps as _build_eta_refresh_deps,
    build_eta_background_refresh_deps as _build_eta_background_refresh_deps,
    build_eta_tail_output_deps as _build_eta_tail_output_deps,
    build_eta_tail_snapshot_deps as _build_eta_tail_snapshot_deps,
    build_probe_all_deps as _build_probe_all_deps,
    build_probe_node_deps as _build_probe_node_deps,
    build_remote_exec_deps as _build_remote_exec_deps,
    build_running_lifecycle_deps as _build_running_lifecycle_deps,
    build_running_probe_snapshot_deps as _build_running_probe_snapshot_deps,
    build_sudo_cpu_batch_probe_deps as _build_sudo_cpu_batch_probe_deps,
    build_terminal_diagnostics_snapshot_deps as _build_terminal_diagnostics_snapshot_deps,
    build_update_running_tasks_deps as _build_update_running_tasks_deps,
    build_windows_host_extras_deps as _build_windows_host_extras_deps,
    build_windows_node_probe_deps as _build_windows_node_probe_deps,
)
from scheduler_running.lifecycle import (
    RunningLifecycleDeps as _RunningLifecycleDeps,
    apply_alive_probe_result as _apply_alive_probe_result,
    check_running_probe_result as _check_running_probe_result_impl,
    handle_dead_probe_result as _handle_dead_probe_result,
    handle_unknown_probe_result as _handle_unknown_probe_result,
)
from scheduler_runtime.history_record import (
    RuntimeHistoryRecordDeps as _RuntimeHistoryRecordDeps,
    runtime_history_record as _runtime_history_record_impl,
)
from scheduler_runtime.profile import (
    RuntimeProfileDeps as _RuntimeProfileDeps,
    apply_runtime_projection as _apply_runtime_projection_impl,
    apply_test_log_runtime_profile as _apply_test_log_runtime_profile_impl,
    load_eta_tracker_module as _load_eta_tracker_module_impl,
    read_text_tail as _read_text_tail_impl,
    runtime_profile_from_log as _runtime_profile_from_log_impl,
    runtime_total_units_from_cmd as _runtime_total_units_from_cmd_impl,
)
from scheduler_runtime.identity import (
    candidate_runtime_seconds as _candidate_runtime_seconds_impl,
    runtime_device_kind_for_task as _runtime_device_kind_for_task_impl,
    runtime_node_bucket_key as _runtime_node_bucket_key_impl,
    runtime_node_bucket_keys as _runtime_node_bucket_keys_impl,
    task_runtime_keys as _task_runtime_keys_impl,
    task_runtime_payload as _task_runtime_payload_impl,
)
from scheduler_probe.sudo_cpu import (
    SudoCpuBatchProbeDeps as _SudoCpuBatchProbeDeps,
    cpu_only_sudo_probe_cmd as _cpu_only_sudo_probe_cmd_impl,
    parse_cpu_only_sudo_probe as _parse_cpu_only_sudo_probe_impl,
    probe_sudo_cpu_nodes_batch as _probe_sudo_cpu_nodes_batch_impl,
)
from scheduler_windows.host_extras import (
    WindowsHostExtrasDeps as _WindowsHostExtrasDeps,
    probe_windows_host_extras as _probe_windows_host_extras_impl,
)
from scheduler_failure.final_model_success import (
    FinalModelSuccessDeps as _FinalModelSuccessDeps,
    terminal_final_model_success as _terminal_final_model_success_impl,
)
from scheduler_failure.local_oom_detection import (
    LocalOomKillDetectionDeps as _LocalOomKillDetectionDeps,
    detect_oom_kills_local as _detect_oom_kills_local_impl,
)
from scheduler_failure.log_success_scan import (
    FullLogSuccessScanDeps as _FullLogSuccessScanDeps,
    scan_full_log_for_success as _scan_full_log_for_success_impl,
)
from scheduler_failure.terminal_diagnosis import (
    TerminalDiagnosisDeps as _TerminalDiagnosisDeps,
    diagnose_terminal as _diagnose_terminal_impl,
)
from scheduler_failure.terminal_finalize import (
    TerminalFinalizeDeps as _TerminalFinalizeDeps,
    try_finalize_terminal_local_task as _try_finalize_terminal_local_task_impl,
)

__all__ = [
    name
    for name in globals()
    if name != "__all__" and not (name.startswith("__") and name.endswith("__"))
]
