"""Compatibility import bundle for scheduler.py.

Generated by splitting scheduler_compat_imports.py into domain-oriented import surfaces.
"""

from __future__ import annotations

from scheduler_adopt.command import (
    AdoptCommandDeps as _AdoptCommandDeps,
    cmd_adopt as _cmd_adopt_impl,
)
from scheduler_commands.bulk_submit import (
    BulkSubmitDeps as _BulkSubmitDeps,
    CpuBatchSubmitDeps as _CpuBatchSubmitDeps,
    build_bulk_submit_task as _build_bulk_submit_task_impl,
    build_bulk_submit_tasks as _build_bulk_submit_tasks_impl,
    build_cpu_batch_submit_spec as _build_cpu_batch_submit_spec_impl,
    bulk_submit_result_conflict_message as _bulk_submit_result_conflict_message,
    load_submit_jsonl_specs_from_text as _load_submit_jsonl_specs_from_text,
    spec_bool as _bulk_spec_bool,
    spec_int as _bulk_spec_int,
)
from scheduler_submit.cpu_batch import (
    CpuBatchSubmitValidationDeps as _CpuBatchSubmitValidationDeps,
    SubmitCpuBatchCommandDeps as _SubmitCpuBatchCommandDeps,
    cmd_submit_cpu_batch as _cmd_submit_cpu_batch_impl,
    validate_cpu_batch_submit_spec as _validate_cpu_batch_submit_spec_impl,
)
from scheduler_submit.command import (
    SubmitCommandDeps as _SubmitCommandDeps,
    SubmitJsonlCommandDeps as _SubmitJsonlCommandDeps,
    cmd_submit as _cmd_submit_impl,
    cmd_submit_jsonl as _cmd_submit_jsonl_impl,
)
from scheduler_submit.policy import (
    abs_under as _abs_under_impl,
    arg_value as _arg_value_impl,
    bapr_batch_projection as _bapr_batch_projection_impl,
    bapr_run_seed_metas_from_cmd as _bapr_run_seed_metas_from_cmd_impl,
    candidate_training_source_paths as _candidate_training_source_paths_impl,
    checkpoint_contract_reason as _checkpoint_contract_reason_impl,
    cmd_explicitly_cpu as _cmd_explicitly_cpu_impl,
    cmd_has_resume_flag as _cmd_has_resume_flag_impl,
    cmd_looks_like_training as _cmd_looks_like_training_impl,
    cpu_training_policy_reason as _cpu_training_policy_reason_impl,
    expand_simple_seed_loop_inner as _expand_simple_seed_loop_inner_impl,
    extract_script_cd_dir as _extract_script_cd_dir_impl,
    infer_bapr_result_dirs_from_cmd as _infer_bapr_result_dirs_from_cmd_impl,
    infer_bapr_run_seed_ckpt as _infer_bapr_run_seed_ckpt_impl,
    infer_checkpoint_from_submit as _infer_checkpoint_from_submit_impl,
    infer_direct_jax_train_ckpt as _infer_direct_jax_train_ckpt_impl,
    infer_wrapper_ckpt as _infer_wrapper_ckpt_impl,
    resume_capability_reason as _resume_capability_reason_impl,
    safe_read_text as _safe_read_text_impl,
    script_invocation_from_cmd as _script_invocation_from_cmd_impl,
    seed_value_substitute as _seed_value_substitute_impl,
    shell_expand_simple as _shell_expand_simple_impl,
    shell_split_statements as _shell_split_statements_impl,
    simple_shell_env_from_script as _simple_shell_env_from_script_impl,
    split_bapr_seed_batch_submit_args as _split_bapr_seed_batch_submit_args_impl,
    submit_context_is_bapr as _submit_context_is_bapr_impl,
    submit_policy_text as _submit_policy_text_impl,
    task_looks_like_training as _task_looks_like_training_impl,
)
from scheduler_task.identity import (
    TaskIdentityDeps as _TaskIdentityDeps,
    active_or_unsynced_result_status as _active_or_unsynced_result_status_impl,
    conflict_path_key as _conflict_path_key_impl,
    legacy_external_state_is_terminal as _legacy_external_state_is_terminal_impl,
    local_launch_transport_alive as _local_launch_transport_alive_impl,
    recorded_launch_safety_state as _recorded_launch_safety_state_impl,
    same_declared_path as _same_declared_path_impl,
    same_run_identity_live_artifact_reason as _same_run_identity_live_artifact_reason_impl,
    slurm_state_is_terminal as _slurm_state_is_terminal_impl,
    task_has_recorded_launch_artifacts as _task_has_recorded_launch_artifacts_impl,
    task_run_identity as _task_run_identity_impl,
)
from scheduler_task.lineage import (
    cancel_related_queued_retries as _cancel_related_queued_retries_impl,
    has_user_cancelled_retry_descendant as _has_user_cancelled_retry_descendant_impl,
    mark_user_cancelled as _mark_user_cancelled_impl,
    reconcile_requeue_lineage_invariants as _reconcile_requeue_lineage_invariants_impl,
    remember_last_placement as _remember_last_placement_impl,
    task_is_descendant_of as _task_is_descendant_of_impl,
)
from scheduler_diagnostics.doctor import (
    DoctorDeps as _DoctorDeps,
    cmd_doctor as _cmd_doctor_impl,
    doctor_issue as _doctor_issue_impl,
    doctor_path_key as _doctor_path_key_impl,
    doctor_scan_state as _doctor_scan_state_impl,
    flag_present_or_true as _flag_present_or_true_impl,
    flag_values_any as _flag_values_any_impl,
    ready_local_file as _ready_local_file_impl,
    resolve_cmd_path as _resolve_cmd_path_impl,
    simple_sac_ckpt_for_method as _simple_sac_ckpt_for_method_impl,
    simple_sac_eval_prereq_files as _simple_sac_eval_prereq_files_impl,
    simple_sac_large_data_reason as _simple_sac_large_data_reason_impl,
    simple_sac_train_best_ckpt_from_cmd as _simple_sac_train_best_ckpt_from_cmd_impl,
    task_has_wait_file as _task_has_wait_file_impl,
    task_wait_files as _task_wait_files_impl,
)
from scheduler_commands.edit import (
    EditCommandDeps as _EditCommandDeps,
    cmd_edit as _cmd_edit_impl,
)
from scheduler_runtime.history import (
    HistoryCommandDeps as _HistoryCommandDeps,
    ResourceHistoryDeps as _ResourceHistoryDeps,
    RuntimeHistoryLookupDeps as _RuntimeHistoryLookupDeps,
    cmd_history as _cmd_history_impl,
    history_eta_for_task as _history_eta_for_task_impl,
    history_get as _history_get_impl,
    history_record as _history_record_impl,
    is_oom_like_task as _is_oom_like_task_impl,
    percentile as _percentile_impl,
    runtime_cmd_tokens as _runtime_cmd_tokens_impl,
    runtime_history_best as _runtime_history_best_impl,
    runtime_history_closest as _runtime_history_closest_impl,
    runtime_history_closest_index as _runtime_history_closest_index_impl,
    runtime_script_name as _runtime_script_name_impl,
    runtime_total_history_s as _runtime_total_history_s_impl,
    runtime_walltime_for_task as _runtime_walltime_for_task_impl,
    seed_pending_eta_from_history as _seed_pending_eta_from_history_impl,
    task_duration_s as _task_duration_s_impl,
    task_has_progress_marker as _task_has_progress_marker_impl,
    untrusted_startup_oom_sample as _untrusted_startup_oom_sample_impl,
)
from scheduler_commands.status import (
    StatusCommandDeps as _StatusCommandDeps,
    compact_status_task as _compact_status_task_impl,
    filter_status_tasks as _filter_status_tasks,
    format_eta_load_seconds as _format_eta_load_seconds,
    format_task_runtime_minutes as _format_task_runtime_minutes,
    parse_status_filter_ids as _parse_status_filter_ids,
    cmd_status as _cmd_status_impl,
    status_json_payload as _status_json_payload,
    status_rows_for_display as _status_rows_for_display,
)
from scheduler_commands.wait_for import (
    WaitForDeps as _WaitForDeps,
    cmd_wait_for as _cmd_wait_for_impl,
)
from scheduler_commands.why import (
    WhyCommandDeps as _WhyCommandDeps,
    cmd_why as _cmd_why_impl,
    explain_node_fit as _explain_node_fit_impl,
)
from scheduler_submit.preflight import (
    SubmitPreflightDeps as _SubmitPreflightDeps,
    SubmitPreflightRefusal as _SubmitPreflightRefusal,
    run_submit_preflight as _run_submit_preflight,
)
from scheduler_submit.task import (
    SubmitTaskDeps as _SubmitTaskDeps,
    SubmitTaskRefusal as _SubmitTaskRefusal,
    build_submit_task_for_state as _build_submit_task_for_state,
)
from scheduler_probe.profile_local import (
    ProfileLocalDeps as _ProfileLocalDeps,
    cmd_profile_local as _cmd_profile_local_impl,
)
from scheduler_task.log import tail_task_log as _tail_task_log_impl
from scheduler_control.commands import (
    ControlCommandDeps as _ControlCommandDeps,
    cmd_claims as _cmd_claims_impl,
    cmd_compact as _cmd_compact_impl,
    cmd_priority as _cmd_priority_impl,
    cmd_show as _cmd_show_impl,
    cmd_task_log as _cmd_task_log_impl,
)
from scheduler_result.discovery import (
    ResultArtifactDeps as _ResultArtifactDeps,
    ResultsCommandDeps as _ResultsCommandDeps,
    apply_discovered_result_artifacts as _apply_discovered_result_artifacts_impl,
    bash_path_arg as _bash_path_arg_impl,
    clean_result_path as _clean_result_path_impl,
    cmd_results as _cmd_results_impl,
    cmd_flag_values as _cmd_flag_values_impl,
    cmd_flag_values_from_cmd as _cmd_flag_values_from_cmd_impl,
    cmd_token_variants as _cmd_token_variants_impl,
    discover_result_artifacts as _discover_result_artifacts_impl,
    final_model_file_groups_from_cmd as _final_model_file_groups_from_cmd_impl,
    mtimes_match_task_window as _mtimes_match_task_window_impl,
    print_result_artifacts as _print_result_artifacts_impl,
    record_result_artifacts as _record_result_artifacts_impl,
    resolve_task_path as _resolve_task_path_impl,
    result_artifacts_from_cmd as _result_artifacts_from_cmd_impl,
    result_kind_for_path as _result_kind_for_path_impl,
    save_root_run_name_pairs_from_cmd as _save_root_run_name_pairs_from_cmd_impl,
    task_result_artifacts_for_display as _task_result_artifacts_for_display_impl,
    terminal_result_artifact_success as _terminal_result_artifact_success_impl,
)
from scheduler_task.control import (
    TaskControlDeps as _TaskControlDeps,
    cmd_cancel as _cmd_cancel_impl,
    cmd_clear_queue as _cmd_clear_queue_impl,
    cmd_forget as _cmd_forget_impl,
)

__all__ = [
    name
    for name in globals()
    if name != "__all__" and not (name.startswith("__") and name.endswith("__"))
]
