"""Compatibility import bundle for scheduler.py.

Generated by splitting scheduler_compat_imports.py into domain-oriented import surfaces.
"""

from __future__ import annotations

from scheduler_migration.checkpoint import (
    CheckpointMigrationDeps as _CheckpointMigrationDeps,
    checkpoint_migration_extra_allowed_nodes as _checkpoint_migration_extra_allowed_nodes_impl,
)
from scheduler_cpu.plan import (
    apply_cpu_parallel_plan_to_task as _apply_cpu_parallel_plan_to_task_impl,
    apply_cpu_slot_accounting_to_nodes as _apply_cpu_slot_accounting_to_nodes_impl,
    ceil_div as _ceil_div_impl,
    cpu_batch_log_payload as _cpu_batch_log_payload_impl,
    cpu_batch_plan as _cpu_batch_plan_impl,
    cpu_max_workers_per_process as _cpu_max_workers_per_process_impl,
    cpu_parallel_env as _cpu_parallel_env_impl,
    cpu_parallel_template_values as _cpu_parallel_template_values_impl,
    cpu_planning_cores_for_node as _cpu_planning_cores_for_node_impl,
    cpu_wave_summary as _cpu_wave_summary_impl,
    cpu_worker_plan_for_items as _cpu_worker_plan_for_items_impl,
    declared_cpu_slot_floor as _declared_cpu_slot_floor_impl,
    format_cpu_parallel_template as _format_cpu_parallel_template_impl,
    node_physical_cores as _node_physical_cores_impl,
    reserved_cpu_slots_for_task as _reserved_cpu_slots_for_task_impl,
    rewrite_cpu_parallel_cmd as _rewrite_cpu_parallel_cmd_impl,
)
from scheduler_dispatch.core import (
    DispatchAccountingDeps as _DispatchAccountingDeps,
    build_dispatch_queue_plan as _build_dispatch_queue_plan,
    prepare_dispatch_node_accounting as _prepare_dispatch_node_accounting,
)
from scheduler_dispatch.launch_staging import (
    DispatchLaunchStagingDeps as _DispatchLaunchStagingDeps,
    apply_launch_input_staging_gate as _apply_launch_input_staging_gate,
    apply_launch_staging_gate as _apply_launch_staging_gate,
)
from scheduler_dispatch.launch_execution import (
    DispatchLaunchExecutionDeps as _DispatchLaunchExecutionDeps,
    apply_dispatch_launch_execution as _apply_dispatch_launch_execution,
)
from scheduler_dispatch.loop import (
    DispatchLoopDeps as _DispatchLoopDeps,
    do_dispatch as _do_dispatch_impl,
)
from scheduler_dispatch.command import (
    DispatchCommandDeps as _DispatchCommandDeps,
    run_dispatch_command as _run_dispatch_command,
)
from scheduler_dispatch.watch_wiring import (
    build_dispatch_accounting_deps as _build_dispatch_accounting_deps,
    build_dispatch_command_deps as _build_dispatch_command_deps,
    build_dispatch_launch_execution_deps as _build_dispatch_launch_execution_deps,
    build_dispatch_launch_staging_deps as _build_dispatch_launch_staging_deps,
    build_dispatch_loop_deps as _build_dispatch_loop_deps,
    build_dispatch_placement_apply_deps as _build_dispatch_placement_apply_deps,
    build_dispatch_resume_placement_deps as _build_dispatch_resume_placement_deps,
    build_dispatch_task_gate_deps as _build_dispatch_task_gate_deps,
    build_resource_estimate_deps as _build_resource_estimate_deps,
    build_watch_command_deps as _build_watch_command_deps,
    build_watch_iteration_deps as _build_watch_iteration_deps,
    build_watch_state_phase_deps as _build_watch_state_phase_deps,
)
from scheduler_external.reconcile import (
    ExternalReconcileDeps as _ExternalReconcileDeps,
    reconcile_external_tasks as _reconcile_external_tasks_impl,
)
from scheduler_resource.forensics import (
    ResourceForensicsDeps as _ResourceForensicsDeps,
    build_crash_forensics_payload as _build_crash_forensics_payload_impl,
    build_oom_forensics_payload as _build_oom_forensics_payload_impl,
    ckpt_task_evict_protected as _ckpt_task_evict_protected_impl,
    is_oom_like_forensics as _is_oom_like_forensics_impl,
    log_progress_forensics as _log_progress_forensics_impl,
    remember_running_resource_snapshots as _remember_running_resource_snapshots_impl,
    resource_snapshot_for_placement as _resource_snapshot_for_placement_impl,
    summarize_task_for_resource_log as _summarize_task_for_resource_log_impl,
    task_evict_loss_protected as _task_evict_loss_protected_impl,
    task_has_incremental_result_resume as _task_has_incremental_result_resume_impl,
    task_has_progress_evidence as _task_has_progress_evidence_impl,
    task_has_resume_evidence as _task_has_resume_evidence_impl,
    task_progress_ratio as _task_progress_ratio_impl,
    task_ram_pressure_mb as _task_ram_pressure_mb_impl,
)
from scheduler_placement_engine.helpers import (
    assign_windows_pin_plan as _assign_windows_pin_plan_impl,
    clear_disallowed_cpu_fallback_selection as _clear_disallowed_cpu_fallback_selection_impl,
    flag_enabled as _flag_enabled_impl,
    gpu_freeze_line_mb as _gpu_freeze_line_mb_impl,
    gpu_threshold_snapshot as _gpu_threshold_snapshot_impl,
    ignore_cpu_for_server_gpu_task as _ignore_cpu_for_server_gpu_task_impl,
    node_gpu_util_limit as _node_gpu_util_limit_impl,
    node_ram_headroom_mb as _node_ram_headroom_mb_impl,
    node_ram_snapshot as _node_ram_snapshot_impl,
    task_ignores_one_third_pack_rule as _task_ignores_one_third_pack_rule_impl,
    task_is_gpu_capacity_task as _task_is_gpu_capacity_task_impl,
    task_launch_cpu_mode as _task_launch_cpu_mode_impl,
)
from scheduler_failure.crash_requeue import (
    CrashRequeueDeps as _CrashRequeueDeps,
    requeue_after_crash as _requeue_after_crash_impl,
)
from scheduler_placement_engine.post_dispatch_thresholds import (
    PostDispatchThresholdDeps as _PostDispatchThresholdDeps,
    enforce_post_dispatch_thresholds as _enforce_post_dispatch_thresholds_impl,
)
from scheduler_placement_engine.eviction import (
    EvictionDeps as _EvictionDeps,
    evict_node_cooldown_block_reason as _evict_node_cooldown_block_reason_impl,
    evict_to_queue as _evict_to_queue_impl,
    eviction_cooldown_block_reason as _eviction_cooldown_block_reason_impl,
)
from scheduler_placement_engine.preemption import (
    PreemptionDeps as _PreemptionDeps,
    preempt_for_high_priority as _preempt_for_high_priority_impl,
)
from scheduler_dispatch.placement_apply import (
    DispatchPlacementApplyDeps as _DispatchPlacementApplyDeps,
    apply_dispatch_placement as _apply_dispatch_placement,
)
from scheduler_migration.dispatch_resume_placement import (
    DispatchResumePlacementDeps as _DispatchResumePlacementDeps,
    resolve_resume_aware_placement as _resolve_resume_aware_placement,
    validate_selected_resume_checkpoint as _validate_selected_resume_checkpoint,
)
from scheduler_dispatch.task_gates import (
    DispatchTaskGateDeps as _DispatchTaskGateDeps,
    apply_dispatch_task_gates as _apply_dispatch_task_gates,
)
from scheduler_node.inventory import (
    BUS_TORCH_CMD_REWRITES,
    JTL110GPU_RE_SAC_JAX_ENV,
    JTL110GPU_RE_SAC_JAX_NVIDIA_LIBS,
    JTL110GPU_RE_SAC_JAX_PATH,
    JTL110GPU_RE_SAC_JAX_SITE,
    NODES,
    NODE007_RESAC_JAX_ENV,
    NODE007_SCOMP_ENV,
    NODE_NAME_ALIASES,
    OFFLINE_SUMO_ENV,
    OFFLINE_SUMO_PYTHON,
    TASK_NODE_FIELDS as _TASK_NODE_FIELDS,
    TASK_NODE_LIST_FIELDS as _TASK_NODE_LIST_FIELDS,
    canonical_node_name as _canonical_node_name_impl,
    canonicalize_node_list as _canonicalize_node_list_impl,
    canonicalize_state_node_names as _canonicalize_state_node_names_impl,
)
from scheduler_node.gates import (
    BlockedNodesDeps as _BlockedNodesDeps,
    NodeResourceGateDeps as _NodeResourceGateDeps,
    blocked_nodes_for_signature as _blocked_nodes_for_signature_impl,
    blocked_nodes_for_task as _blocked_nodes_for_task_impl,
    gpu_task_cap_for_task as _gpu_task_cap_for_task_impl,
    hpc_cpu_pool_soft_require_nodes as _hpc_cpu_pool_soft_require_nodes_impl,
    launch_failed_nodes_for_task as _launch_failed_nodes_for_task_impl,
    local_cpu_pressure_high as _local_cpu_pressure_high_impl,
    local_gpu_cpu_block_reason as _local_gpu_cpu_block_reason_impl,
    node_concurrency_cap_for_task as _node_concurrency_cap_for_task_impl,
    node_cpu_fallback_block_reason as _node_cpu_fallback_block_reason_impl,
    node_gpu_task_block_reason as _node_gpu_task_block_reason_impl,
    node_numeric as _node_numeric_impl,
    node_resources_ok as _node_resources_ok_impl,
    node_schedulable_cpu_free as _node_schedulable_cpu_free_impl,
    node_thread_pressure_block_reason as _node_thread_pressure_block_reason_impl,
    task_capability_text as _task_capability_text_impl,
    task_cpu_fallback_capability as _task_cpu_fallback_capability_impl,
    task_gpu_capability as _task_gpu_capability_impl,
    task_is_thread_heavy_jax_cpu as _task_is_thread_heavy_jax_cpu_impl,
    task_required_gpu_idx as _task_required_gpu_idx_impl,
)
from scheduler_node.reporting import (
    NodeReportingDeps as _NodeReportingDeps,
    build_heartbeat_payload as _build_heartbeat_payload_impl,
    claim_wait_s as _claim_wait_s_impl,
    format_claim_intent_hint_for_task as _format_claim_intent_hint_for_task_impl,
    format_claim_record as _format_claim_record_impl,
    format_node_claim_summary as _format_node_claim_summary_impl,
    iter_node_summary_nodes as _iter_node_summary_nodes_impl,
    node_summary_sort_key as _node_summary_sort_key_impl,
    node_summary_visible as _node_summary_visible_impl,
    print_node_summary as _print_node_summary_impl,
)
from scheduler_resource.estimates import (
    description_sibling_resource_estimate_index as _description_sibling_resource_estimate_index_impl,
    description_sibling_resource_estimate as _description_sibling_resource_estimate_impl,
    EffectiveResourceEstimateDeps as _EffectiveResourceEstimateDeps,
    ResourceEstimateDeps as _ResourceEstimateDeps,
    effective_est_ram as _effective_est_ram_impl,
    effective_est_vram as _effective_est_vram_impl,
    live_sibling_ram_floor as _live_sibling_ram_floor_impl,
    live_sibling_resource_estimate_index as _live_sibling_resource_estimate_index_impl,
    live_sibling_resource_estimate as _live_sibling_resource_estimate_impl,
    maybe_lower_explicit_resource_estimate as _maybe_lower_explicit_resource_estimate_impl,
    refresh_queued_resource_estimates as _refresh_queued_resource_estimates,
    resource_history_metadata as _resource_history_metadata_impl,
    with_resource_slack as _with_resource_slack_impl,
)
from scheduler_resource.accounting import (
    AggregateVramReconcileDeps as _AggregateVramReconcileDeps,
    InflightVramReservationDeps as _InflightVramReservationDeps,
    ResourceAccountingDeps as _ResourceAccountingDeps,
    cpu_ownership_snapshot as _cpu_ownership_snapshot_impl,
    dispatch_cycle_log_payload as _dispatch_cycle_log_payload_impl,
    reconcile_aggregate_only_vram as _reconcile_aggregate_only_vram_impl,
    resource_accounting_payload as _resource_accounting_payload_impl,
    reserve_inflight_vram as _reserve_inflight_vram_impl,
)
from scheduler_placement_engine.core import (
    PlacementRuntime as _PlacementRuntime,
    build_no_fit_reason as _build_no_fit_reason_impl,
    gpu_fits as _placement_gpu_fits,
    pick_placement as _pick_placement_impl,
)

__all__ = [
    name
    for name in globals()
    if name != "__all__" and not (name.startswith("__") and name.endswith("__"))
]
