"""Compatibility import bundle for scheduler.py.

Generated by splitting scheduler_compat_imports.py into domain-oriented import surfaces.
"""

from __future__ import annotations

from scheduler_watch.notifications import (
    notify_dispatch_events as _notify_dispatch_events,
    notify_terminal_transitions as _notify_terminal_transitions,
)
from scheduler_notification.notify import (
    NotifyDeps as _NotifyDeps,
    compact_task_event_payload as _compact_task_event_payload_impl,
    format_feishu as _format_feishu_impl,
    load_feishu_cfg as _load_feishu_cfg_impl,
    notify as _notify_impl,
    send_feishu as _send_feishu_impl,
)
from scheduler_environment.env_smoke import (
    EnvSmokeDeps as _EnvSmokeDeps,
    smoke_test_envs as _smoke_test_envs_impl,
    smoke_test_envs_enabled as _smoke_test_envs_enabled_impl,
)
from scheduler_watch.phases import WatchPhaseRecorder as _WatchPhaseRecorder
from scheduler_watch.state_phase import (
    WatchStatePhaseDeps as _WatchStatePhaseDeps,
    run_watch_state_phase as _run_watch_state_phase,
)
from scheduler_watch.iteration import (
    WatchIterationDeps as _WatchIterationDeps,
    run_watch_iteration as _run_watch_iteration,
)
from scheduler_watch.command import (
    WatchCommandDeps as _WatchCommandDeps,
    cmd_watch_locked as _cmd_watch_locked_impl,
)
from scheduler_watch.transitions import (
    classify_running_terminal_transitions as _classify_running_terminal_transitions,
)
from scheduler_windows.probe import (
    WindowsNodeProbeDeps as _WindowsNodeProbeDeps,
    collect_windows_probe_targets as _collect_windows_probe_targets,
    normalize_windows_json_rows as _normalize_windows_json_rows,
    probe_windows_node as _probe_windows_node_impl,
    windows_log_exit_probe_script as _windows_log_exit_probe_script,
    windows_log_exit_probe_specs as _windows_log_exit_probe_specs,
    windows_log_exit_results_from_rows as _windows_log_exit_results_from_rows,
    windows_process_probe_script as _windows_process_probe_script,
    windows_process_probe_specs as _windows_process_probe_specs,
    windows_process_results_from_rows as _windows_process_results_from_rows,
    windows_queue_accounting_fallback_result as _windows_queue_accounting_fallback_result,
)
from scheduler_windows.backend import (
    WindowsBackend as _WindowsBackendImpl,
    WindowsBatchProbeDeps as _WindowsBatchProbeDeps,
    WindowsBackendRuntimeDeps as _WindowsBackendRuntimeDeps,
    WindowsLaunchDeps as _WindowsLaunchDeps,
    windows_backend_batch_probe as _windows_backend_batch_probe_impl,
    windows_backend_launch as _windows_backend_launch_impl,
)
from scheduler_windows.launcher import (
    WINDOWS_DETACHER as _WINDOWS_DETACHER,
    WINDOWS_LAUNCHER as _WINDOWS_LAUNCHER,
)
from scheduler_watch.watcher_state import (
    initial_watcher_state as _initial_watcher_state,
    live_watcher_pid as _live_watcher_pid,
    plan_watcher_tick as _plan_watcher_tick,
)
from scheduler_watch.shutdown import (
    CONTROL_SUBPROCESS_PGIDS as _CONTROL_SUBPROCESS_PGIDS,
    WatcherShutdownRequested as _WatcherShutdownRequested,
    raise_if_watcher_shutdown as _raise_if_watcher_shutdown,
    register_control_subprocess as _register_control_subprocess,
    request_watcher_shutdown as _request_watcher_shutdown,
    reset_watcher_shutdown as _reset_watcher_shutdown,
    terminate_control_process_group as _terminate_control_process_group,
    unregister_control_subprocess as _unregister_control_subprocess,
)
from scheduler_control.process import (
    is_repo_path as _is_repo_path_impl,
    is_scheduler_control_cmdline as _is_scheduler_control_cmdline_impl,
    is_scheduler_control_process as _is_scheduler_control_process_impl,
)
from scheduler_algorithm.bridge import AlgorithmBridge as _AlgorithmBridge
try:
    from algorithm.oracle_trace import (
        build_candidate_row as _algorithm_trace_candidate_row,
        build_decision_slot as _algorithm_trace_decision_slot,
        log_decision_slot as _algorithm_log_decision_slot,
        make_slot_id as _algorithm_trace_slot_id,
        trace_enabled as _algorithm_trace_enabled,
    )
except Exception:
    _algorithm_trace_candidate_row = None
    _algorithm_trace_decision_slot = None
    _algorithm_log_decision_slot = None
    _algorithm_trace_slot_id = None
    _algorithm_trace_enabled = None

__all__ = [
    name
    for name in globals()
    if name != "__all__" and not (name.startswith("__") and name.endswith("__"))
]
