"""Compatibility import bundle for scheduler.py.

Generated by splitting scheduler_compat_imports.py into domain-oriented import surfaces.
"""

from __future__ import annotations

from scheduler_environment.docker_preload import (
    DockerPreloadDeps as _DockerPreloadDeps,
    preload_docker_images_outside_lock as _preload_docker_images_outside_lock_impl,
)
from scheduler_launch.env import (
    apply_node_cmd_rewrites as _apply_node_cmd_rewrites_impl,
    launch_extra_env as _launch_extra_env_impl,
    node_launch_extra_env as _node_launch_extra_env_impl,
    parse_env as _parse_env_impl,
    project_from_path as _project_from_path_impl,
    project_from_pid as _project_from_pid_impl,
    safe_extra_env_items as _safe_extra_env_items_impl,
    task_needs_jax_launch_env as _task_needs_jax_launch_env_impl,
)
from scheduler_launch.executor import execute_launch_intents as _execute_launch_intents_impl
from scheduler_launch.commit import (
    DeferredLaunchDeps as _DeferredLaunchDeps,
    LaunchCommitDeps as _LaunchCommitDeps,
    commit_deferred_launch_result as _commit_deferred_launch_result_impl,
    commit_deferred_launch_results_batch as _commit_deferred_launch_results_batch_impl,
    execute_deferred_launches as _execute_deferred_launches_impl,
)
from scheduler_launch.result import (
    LaunchResultDeps as _LaunchResultDeps,
    apply_launch_result_to_task as _apply_launch_result_to_task_impl,
)
from scheduler_launch_cwd_staging import (
    CodeTarStagingDeps as _CodeTarStagingDeps,
    LaunchCwdStagingDeps as _LaunchCwdStagingDeps,
    launch_input_stage_key as _launch_input_stage_key_impl,
    launch_input_stage_state as _launch_input_stage_state_impl,
    WindowsTarStagingDeps as _WindowsTarStagingDeps,
    stage_code_tar_for_launch as _stage_code_tar_for_launch_impl,
    stage_cwd_for_launch as _stage_cwd_for_launch_impl,
    stage_input_paths_for_launch as _stage_input_paths_for_launch_impl,
    stage_local_dir_to_windows as _stage_local_dir_to_windows_impl,
    tar_exclude_args as _tar_exclude_args_impl,
)
from scheduler_resume_ckpt_staging import (
    ResumeCkptStagingDeps as _ResumeCkptStagingDeps,
    stage_resume_ckpt_for_launch as _stage_resume_ckpt_for_launch_impl,
)
from scheduler_migration.resume_fit import (
    ResumeFitDeps as _ResumeFitDeps,
    estimate_gpu_fit_wait_seconds as _estimate_gpu_fit_wait_seconds_impl,
    estimate_node_fit_wait_seconds as _estimate_node_fit_wait_seconds_impl,
    record_staged_resume_location as _record_staged_resume_location_impl,
    resume_checkpoint_stage_check as _resume_checkpoint_stage_check_impl,
    resume_ckpt_stage_estimate_seconds as _resume_ckpt_stage_estimate_seconds_impl,
    resume_ckpt_stage_key as _resume_ckpt_stage_key_impl,
    resume_location_for_target as _resume_location_for_target_impl,
    resume_stage_source_for_target as _resume_stage_source_for_target_impl,
    running_tasks_for_node as _running_tasks_for_node_impl,
    task_vram_pressure_mb as _task_vram_pressure_mb_impl,
    task_wait_eta_seconds as _task_wait_eta_seconds_impl,
)
from scheduler_migration.resume_scan import (
    ResumeScanDeps as _ResumeScanDeps,
    allow_initial_resume_scan_error as _allow_initial_resume_scan_error_impl,
    find_resume_on_node as _find_resume_on_node_impl,
    refresh_resume_locations_for_task as _refresh_resume_locations_for_task_impl,
    resume_candidate_is_safe as _resume_candidate_is_safe_impl,
    resume_node_names as _resume_node_names_impl,
    resume_scan_key as _resume_scan_key_impl,
    scan_resume_locations as _scan_resume_locations_impl,
    task_requires_resume_scan as _task_requires_resume_scan_impl,
)
from scheduler_migration.staging import (
    MigrationCandidateStagingDeps as _MigrationCandidateStagingDeps,
    MigrationStagingDeps as _MigrationStagingDeps,
    stage_for_migration as _stage_for_migration_impl,
    stage_migration_candidates_outside_lock as _stage_migration_candidates_outside_lock_impl,
)
from scheduler_migration.policy import (
    MigrationPolicyDeps as _MigrationPolicyDeps,
    compute_node_load_seconds as _compute_node_load_seconds_impl,
    consider_migration as _consider_migration_impl,
    identify_migration_candidates as _identify_migration_candidates_impl,
)
from scheduler_launch.staging_plan import (
    LaunchStagingPlanDeps as _LaunchStagingPlanDeps,
    collect_launch_staging_plan as _collect_launch_staging_plan,
    launch_stage_candidate_key as _launch_stage_candidate_key,
)
from scheduler_launch.staging_runner import (
    LaunchStagingRunnerDeps as _LaunchStagingRunnerDeps,
    stage_launch_candidates_outside_lock as _stage_launch_candidates_outside_lock_impl,
)
from scheduler_launch.recovery import (
    LaunchRecoveryDeps as _LaunchRecoveryDeps,
    StaleLaunchRecoveryDeps as _StaleLaunchRecoveryDeps,
    recover_stale_launching_tasks as _recover_stale_launching_tasks_impl,
    recover_stale_launching_tasks_outside_lock as _recover_stale_launching_tasks_outside_lock_impl,
)
from scheduler_launch.command import (
    inject_python_u as _inject_python_u_impl,
)
from scheduler_backend.local_launch import (
    LocalLaunchDeps as _LocalLaunchDeps,
    local_backend_launch as _local_backend_launch_impl,
)
from scheduler_backend.local_probe import (
    LocalBatchProbeDeps as _LocalBatchProbeDeps,
    local_backend_batch_probe as _local_backend_batch_probe_impl,
)
from scheduler_backend.local_backend import (
    LocalBackend as _LocalBackendImpl,
    LocalBackendRuntimeDeps as _LocalBackendRuntimeDeps,
)
from scheduler_backend.hybrid import (
    HybridBackend as _HybridBackendImpl,
    HybridBackendDeps as _HybridBackendDeps,
)
from scheduler_environment.docker_wrap import (
    DockerWrapDeps as _DockerWrapDeps,
    maybe_wrap_docker as _maybe_wrap_docker_impl,
)
from scheduler_backend.facade import (
    Backend,
    LegacyExternalBackend as _LegacyExternalBackend,
    build_hybrid_backend_deps as _build_hybrid_backend_deps,
    build_local_backend_runtime_deps as _build_local_backend_runtime_deps,
    build_windows_backend_runtime_deps as _build_windows_backend_runtime_deps,
)
from scheduler_backend.runtime import build_backend_runtime as _build_backend_runtime
from scheduler_backend.local_orphan_recovery import (
    LocalOrphanRecoveryDeps as _LocalOrphanRecoveryDeps,
    adopt_live_local_pid_rows as _adopt_live_local_pid_rows_impl,
    recover_queued_live_local_tasks as _recover_queued_live_local_tasks_impl,
    scan_launch_recovery_evidence_on_node as _scan_launch_recovery_evidence_on_node_impl,
    scan_scheduleurm_env_pids_on_node as _scan_scheduleurm_env_pids_on_node_impl,
    try_recover_orphan_local_task as _try_recover_orphan_local_task_impl,
)
from scheduler_recovery.queued_artifact_reconcile import (
    QueuedArtifactReconcileDeps as _QueuedArtifactReconcileDeps,
    queued_launch_artifacts as _queued_launch_artifacts_impl,
    reconcile_queued_launch_artifacts_before_dispatch as _reconcile_queued_launch_artifacts_before_dispatch_impl,
)
from scheduler_probe.node import (
    ProbeNodeDeps as _ProbeNodeDeps,
    probe_node as _probe_node_impl,
)
from scheduler_probe.all import (
    ProbeAllDeps as _ProbeAllDeps,
    probe_all_nodes as _probe_all_nodes_impl,
)

__all__ = [
    name
    for name in globals()
    if name != "__all__" and not (name.startswith("__") and name.endswith("__"))
]
